name: Prod CI

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            rm -rf the-well-maintained-test.dev
            git clone git@github.com:ryancheley/the-well-maintained-test.dev.git

            source /home/twmt/venv/bin/activate

            cd /home/twmt/

            rm -rf /home/twmt/core

            cp -r /root/the-well-maintained-test.dev/ /home/twmt/core

            cp /home/twmt/.env /home/twmt/core/core/.env

            pip -q install -r /home/twmt/core/requirements.txt

            cd /home/twmt/core

            python /home/twmt/core/manage.py migrate

            mkdir /home/twmt/core/static
            mkdir /home/twmt/core/staticfiles

            python /home/twmt/core/manage.py collectstatic --noinput -v0

            systemctl daemon-reload
            systemctl restart core